/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage : {
        'tacos': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/tacosCamaron.png')",
        'bebida2': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/bebida2.png')",
        'bebida1': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/bebida1.png')",
        'alitasBBQ': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/alitas.png')",
        'bebida4': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/bebida4.png')",
        'hamburguesa': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/Hamburguesa.png')",
        'ceviche': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/cevicheChicharron.png')",
        'crumble': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/crumble.png')",
        'bebida3': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/bebida3.png')",
        'bebida5': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/bebida5.png')",
        'elotes': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/elotesCarnudos.png')",
        'nachos': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/nachos.png')",
        'lomo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/lomo.jpeg')",
        'osobuco': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/osobuco.png')",
        'espacio': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/espacio.jpg')",
        'ginTonic': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/gin-tonic-tradicional.jpg')",
        'premio': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/premioHamburguesa.jpg')",
        'margarita': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/margarita-de-mango.jpg')",
        'piñaColada': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/pina-colada.jpg')",
        'kolozoGastrobar': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/kolozo-gastrobar.jpg')",
        'amigos': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/amigos.jpg')",
        'cumple': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/cumpleaños.jpg')",
        'bautizo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/bautizo.jpg')",
        'cumpleDec': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/cumpleañosDec.jpg')",
        'deco': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/deco.jpg')",
        'emperador': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/emperador.jpg')",
        'decoBautizo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/decoracionBautizo.jpg')",
        'beerKolozo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/kolozoBeer.jpg')",
        'hamburguesa2': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/hamburguesa2.jpg')",
        'decoracion2': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/decoracion.jpg')",
        'kolozoSitio': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/kolozoSitio.jpg')",
        'decoracion': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/decoracion.png')",
        'marimondas2' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/marimondas2.jpg')",
        'kolozoom' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/kolozoZoom.jpg')",
        'fondo' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/fondo.jpg')",
        'hamburguesaGanadora' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/hamburguesaGanadora.jpg')",
        'celebracion' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/celebracion.jpg')",
        'aniversario' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/aniversario.jpg')",
        'amigos2' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/amigos2.jpg')",
        'marimondas' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/marimondas.jpg')",
        'almuerzo' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/almuerzo.jpg')",
        'mujeres' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/pictures/mujeres.jpg')",
      },
      fontFamily : {
        norse: ['Norsebold', 'static']
      }
    },
  },
  plugins: [],
}