/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage : {
        'alitas': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/alitas.png')",
        'hamburguesa': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/Hamburguesa.png')",
        'tacos': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/tacosCamaron.png')",
        'bebida1': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/bebida1.png')",
        'bebida2': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/bebida2.png')",
        'bebida3': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/bebida3.png')",
        'bebida4': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/bebida4.png')",
        'bebida5': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/bebida5.png')",
        'ceviche': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/cevicheChicharron.png')",
        'crumble': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/crumble.png')",
        'lomo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/lomo.jpeg')",
        'elotes': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/elotesCarnudos.png')",
        'nachos': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/nachos.png')",
        'osobuco': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/osobuco.png')",
        'espacio': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/espacio.jpg')",
        'ginTonic': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/gin-tonic-tradicional.jpg')",
        'premio': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/premioHamburguesa.jpg')",
        'margarita': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/margarita-de-mango.jpg')",
        'piñaColada': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/pina-colada.jpg')",
        'kolozoGastrobar': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/kolozo-gastrobar.jpg')",
        'amigos': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/amigos.jpg')",
        'cumple': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/cumpleaños.jpg')",
        'bautizo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/bautizo.jpg')",
        'cumpleDec': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/cumpleañosDec.jpg')",
        'deco': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/deco.jpg')",
        'decoBautizo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/decoracionBautizo.jpg')",
        'emperador': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/emperador.jpg')",
        'hamburguesa2': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/hamburguesa2.jpg')",
        'beerKolozo': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/kolozoBeer.jpg')",
        'kolozoSitio': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/kolozoSitio.jpg')",
        'decoracion2': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/decoracion.jpg')",
        'decoracion': "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/decoracion.png')",
        'kolozoom' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/kolozoZoom.jpg')",
        'HamburguesaGanadora' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/hamburguesaGanadora.jpg')",
        'fondo' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/fondo.jpg')",
        'aniversario' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/aniversario.jpg')",
        'amigos2' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/amigos2.jpg')",
        'celebracion' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/celebracion.jpg')",
        'almuerzo' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/almuerzo.jpg')",
        'marimondas' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/marimondas.jpg')",
        'marimondas2' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/marimondas2.jpg')",
        'mujeres' : "url('C:/Users/Usuario/Desktop/Repos/Kolozo/src/assets/images/mujeres.jpg')",
      },
      fontFamily : {
        norse: ['Norsebold', 'static']
      }
    },
  },
  plugins: [],
}